### ISSUE TITLE
 how to use Multimap object with REST call?

### ISSUE THREAD

**Issue by Milstein** [leveluplunch/levelup-java-examples#1]
Hi,

I created Multimap like this:

Multimap<String, Multimap<String, Multimap<String, String>>> htUser = LinkedListMultimap.create();

My inspection shows the value of this htUser as :
{Engineering=[{Computer Engineering=[{Non-tenure-track research faculty=[Visiting Associate Professor]}]}], Science=[{Physics=[{Tenured/tenure-track faculty=[Professor]}]}, {Physics=[{Tenured/tenure-track faculty=[Distinguished Professor]}]}]}

But, when I try to return the value to REST call using AJAX, it returns just :
[{"positions":{"empty":false}}]
Have you face this issue? how to fix this to bind the Multimap object using REST call?

**Comment by justinmusgrove** [comment]
Hey @Milstein, I commented [here](http://www.leveluplunch.com/java/examples/guava-multimap-example/#comment-2302408915), let me know if that helps.

**Comment by justinmusgrove** [comment]
Closing, lack of response
